allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': false
  '@prisma/engines': false
  '@tsparticles/engine': false
  '@vercel/speed-insights': set this to true or false
  canvas: false
  core-js: false
  core-js-pure: false
  esbuild: false
  protobufjs: false
  puppeteer: false
  sharp: false
  unrs-resolver: false
